### ISSUE TITLE
Renew landing page

### ISSUE THREAD

**Issue by zeckli** [thematters/billboard-app#1]
### Description
Renew landing page content and illustration according new plan of Billboard.

### Todos
- [x] Update landing page design and copies
- [x] Update NFT showcase
- [x] Create QF card component

### Stories
- https://github.com/thematters/developer-resource/issues/353
